### ISSUE TITLE
Modal hidden

### ISSUE THREAD

**Issue by nolafs** [homerjam/angular-gsapify-router#14]
Hi,

Trying to use the router to open and close modal which overlays the site. Looking at the source it should only make the view visible onStart but it seems to start the animation right away. How can make it stay hidden on initialisation and only visible when I add child view?

Cheers
Olaf

**Comment by homerjam** [comment]
Hi Olaf,

I would look at adjusting your views and states to accommodate this, consider the following:

```html
<!-- index.html -->
<body>

<div ui-view="main">

    <div ui-view="modal" class="gsapify-router"></div>

    <div ui-view="content" class="gsapify-router"></div>

</div>

</body>
```

```js

angular.module('myApp').config(function($stateProvider, gsapifyRouterProvider){

    $stateProvider.state('main', {
        abstract: true,
        views: {
            main: {}
        }
    });

    $stateProvider.state('main.home', {
        url: '/',
        views: {
            content: {
                templateUrl: 'home.html'
            }
        }
    });    

    $stateProvider.state('main.home.modal', {
        url: '/modal',
        views: {
            'modal@': {
                templateUrl: 'modal.html'
            }
        },
        data: {
            'gsapifyRouter.modal': {
                // transition config here
            }
        }
    });

});
```

You'll need to add the appropriate css to ensure your modal view is above your content view when in use, I'd suggest adding the state name to the body on the `$stateChangeSuccess` event to do this perhaps.

Hope this helps

James

**Comment by nolafs** [comment]
Thanks, 

That solved the issue. I pretty new to angular and still need get my head around it. Really appreciate your help.

Cheers
Olaf

**Comment by homerjam** [comment]
No problem!
