### ISSUE TITLE
What's the src file?

### ISSUE THREAD

**Issue by aeikman** [homerjam/angular-gsapify-router#16]
I'm new to bower so perhaps I may be missing something that is obvious.
Either way, what is the src file to link to in the index, so that I can inject 'hj.gsapifyRouter'?

**Comment by homerjam** [comment]
I'm not quite sure how you're using bower - I've never needed to know the src file. The main file (as indicated in the bower.json) is angular-gsapify-router.js. If you can provide info on what you're trying to do or link to a tutorial you're following perhaps I can help more.

**Comment by aeikman** [comment]
A pure oversight on my part.  I'm used to seeing a statement on loading the script file into application such as '<script src="./bower_components/angular-gsapify-router/angular-gsapify-router.js"></script>',  in the readme.  

I'm really looking forward to using this directive. Thanks.
