### ISSUE TITLE
Issues with transitions and ui-view

### ISSUE THREAD

**Issue by Karnith** [homerjam/angular-gsapify-router#17]
There seems to be a bug, unless it's by designed, that your directive won't work with data-ui-view. Only ui-view seems to work and apply transitions.

I've tried both:

<div ui-view="content" class="gsapify-router" autoscroll="false"></div> --- works
<div data-ui-view="content" class="gsapify-router" autoscroll="false"></div> --breaks and uses default transiiton if set.

**Comment by homerjam** [comment]
Not by design, just oversight!
