### ISSUE TITLE
Using resolve inside the router gives gsapifyRouterBlankState error

### ISSUE THREAD

**Issue by sebastiannm** [homerjam/angular-gsapify-router#22]
Hi,
I get the error 'Could not resolve '' from state 'gsapifyRouterBlankState'' when using a resolve promise. Even if the time to resolve is 0

I edited a working plunker I found and I added the resolve example
http://plnkr.co/edit/YyMExg?p=preview

**Comment by homerjam** [comment]
Thanks for reporting this. There was an issue when using `initialTransitionEnabled` which uses a hack to force trigger the first transition.
