### ISSUE TITLE
Slider previous and next

### ISSUE THREAD

**Issue by nolafs** [homerjam/angular-gsapify-router#23]
Hi 

How would go about implementing a slider. Can I pass in something to apply a reversed animation when the I click there previous button?

Cheers
Olaf

**Comment by homerjam** [comment]
Hi Olaf,

Yep - check out this site which does exactly that https://www.neue-london.com/collections/ss16?dir=previous

Here is the snippet I'm using:

```
data: {
    'gsapifyRouter.collections':
      enter: {
        'in': function ($state, $stateParams) {
          if ($stateParams.dir === 'next') {
            return {
              transition: 'slideLeft',
              priority: 3
            };
          } else {
            return {
              transition: 'slideRight',
              priority: 3
            };
          }
        },
        'out': function ($state, $stateParams) {
          if ($stateParams.dir === 'next') {
            return {
              transition: 'slideRight',
              priority: 3
            };
          } else {
            return {
              transition: 'slideLeft',
              priority: 3
            };
          }
        }
      }
    }
}
```

In the links (`ui-sref` directive) I'm setting the next/previous parameter.

Hope that helps.

James

**Comment by nolafs** [comment]
Hi James,

Great, thank you.

Cheers
Olaf

On 11 Mar 2016, at 16:10, James Homer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Olaf,

Yep - check out this site which does exactly that https://www.neue-london.com/collections/ss16?dir=previous

Here is the snippet I'm using:

data: {
    'gsapifyRouter.collections':
      enter: {
        'in': function ($state, $stateParams) {
          if ($stateParams.dir === 'next') {
            return {
              transition: 'slideLeft',
              priority: 3
            };
          } else {
            return {
              transition: 'slideRight',
              priority: 3
            };
          }
        },
        'out': function ($state, $stateParams) {
          if ($stateParams.dir === 'next') {
            return {
              transition: 'slideRight',
              priority: 3
            };
          } else {
            return {
              transition: 'slideLeft',
              priority: 3
            };
          }
        }
      }
    }
}


In the links (ui-sref directive) I'm setting the next/previous parameter.

Hope that helps.

James
