### ISSUE TITLE
Leave blocks and priority not honored with ui-router 1.0

### ISSUE THREAD

**Issue by luncht1me** [homerjam/angular-gsapify-router#27]
I cannot get priority to obey what i've set, or to have any leave animations work with the latest ui-router.

Hopefully you haven't ditched the project! I love this plugin but it's causing a lot of inconsistencies for me currently. :( 

Only enter blocks are honored, and priority changes nothing.

**Comment by homerjam** [comment]
Hey @luncht1me can this be closed now?

**Comment by luncht1me** [comment]
@homerjam yeah absolutely. Bare in mind my pull request hasn't tested everything but for this issue it seems resolved.

Priority is also untested, but judging by what I had to change, I'm -assuming- it'll work.

**Comment by homerjam** [comment]
Great, thanks again for the PR.
