### ISSUE TITLE
Add alternative animation for "back" navigation

### ISSUE THREAD

**Issue by skaman** [homerjam/angular-gsapify-router#4]
Hi, playing with the library i can't fit it entirely in my scenario.

If we have an application with a navigation stack ios like, the flow of the views could be defined at runtime. For example an app with 3 screen could have a navigation flow like:
A -> B -> C -> C -> B -> C
Every view have his own "back" button for come back to the previous view, and the animation should be inverted.
Playing with animation priorities i can't find a way to satisfy this need.
I think a solution could be add an alternative animation for "back" transition.

ie:
```
{
     "enter": {
         "in": "right",
         "out": "fadeDelayed"
    },
    "leave": {
        "in": "fadeDelayed",
         "out": "right"
    }
    "back":  {
         "enter": {
             "in": "fadeDelayed",
             "out": "right"
        },
        "leave": {
            "in": "right",
             "out": "fadeDelayed"
        }
    }
}
```

And with some kind of option to set in $stateChangeSuccess event, so the app could define his navigation stack.

Do you think is possible have something like that?
Thanks

**Comment by homerjam** [comment]
Hmm, this is an interesting scenario. I have an idea that may be more flexible but perhaps confusing, something like this:

```javascript
{
     "enter": {
         "in": function(newState, stateHistory){
                return newState === stateHistory[stateHistory.length - 2] ? 'reverseAnimation' : 'normalAnimation';
         },
         "out": "fadeDelayed"
},
```

The above function could also be applied to the `priority` as an alternative.

Or, if the animations are always reversed then something simple like:

```javascript
{
     "enter": {
         "in": "right",
         "out": "fadeDelayed"
    },
    "leave": {
        "in": "fadeDelayed",
         "out": "right"
    },
    "invertBack": true
}
```

Sorry I'm not quite sure what you meant by:
> And with some kind of option to set in $stateChangeSuccess event, so the app could define his navigation stack.

**Comment by skaman** [comment]
I like your first idea! Doesn't seem confusing to me and it's really more flexible.

About this
>And with some kind of option to set in $stateChangeSuccess event, so the app could define his navigation stack.

Sorry, just ignore it :)
