### ISSUE TITLE
Delayed state change after multiple click

### ISSUE THREAD

**Issue by aicokleinovink** [homerjam/angular-gsapify-router#5]
First of all, great work!

There is an issue when clicking multiple times on a ui-sref link. For example, when there is a animated statechange for let's say 0.5 seconds. Clicking the link 10 times will result in a statechange after 5 seconds (didn't really timed it exactly), no matter if you go to any other states during that time. It still will load the clicked state after that period of time. Something wrong with my code, or is this a real issue?

Hope you know what I mean, it shows up in Chrome, Safari works fine. Didn't test it in any other browsers at this time.

**Comment by homerjam** [comment]
Hi,

I'm afraid I can't seem to be able to reproduce this. Can you try the [demo](http://homerjam.github.io/angular-gsapify-router/#/) to see if it still happens?

Otherwise please could you make a fiddle/plunkr to help us distil the problem.

Thanks

**Comment by aicokleinovink** [comment]
Thanks for your reply, have tried the demo and it doesn't seem to show up there. Maybe it's because I have some small errors in my ui-router (some states are not going anywhere yet). Will clean that up and try if I get the same issue after that. Thanks for your reply, think you can close this issue for now. I'll keep you posted if the issue keeps acting up!
