### ISSUE TITLE
Doesn't work in ie 10-11

### ISSUE THREAD

**Issue by dzNavitski** [homerjam/angular-gsapify-router#6]
Hello, thank you for work.
I found that this plugin doesn't work in Internet explorer.
If you have any ideas why it not working, please tell me.

**Comment by dzNavitski** [comment]
On line 106 and 114 if we change 'toString' to 'Object.prototype.toString' all will work great.

**Comment by homerjam** [comment]
@dzNavitski thanks for the solution! I've now updated the plugin
